[env]

[config]
skip_core_tasks = true

[tasks.test]
script = """
"""

[tasks.push]
script = """
git add -A
git commit -m "add"
git push
"""

[tasks.init]
script = """
echo "REPOS_DIR=$(PWD)" > .env
"""
