name: TODO
description: Create TODO memo
title: "input TODO title here"
labels: ["TODO"]

assignees:
  - octocat

body:
  - type: textarea
    id: todo
    attributes:
      label: TODO
      description: TODO description
      placeholder: add TODO here
    validations:
      required: true
